/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AtivPoo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author R I C H
 */
public class Tesr extends javax.swing.JFrame {

    /**
     * Creates new form Tesr
     */
    ProdsMercado[] tes;
    private int cont = 0;
    private int calc = 0;

    public Tesr() {
        initComponents();
    }

 // public boolean  Pesq(int id){
  //     boolean achou = false;
  //     for(int i = 0; i < calc; i ++)
  //   {
  //     if(tes[i].getId() == id){
  //        achou = true;
  //       JOptionPane.showConfirmDialog(rootPane, "Achou ");
  //     }else{
  //       achou = false;
  //       JOptionPane.showConfirmDialog(rootPane, " Não Achou ");
  //       
  //     }
  //   }
    
     // public void incluirProdut(ProdsMercado produtosList){
    //   if(cont < tes.length ){
     //    tes[cont++] = produtosList; 
     //  }else{
     //     System.out.println("Está vazio");
     //  }
  //   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JbtnOK = new javax.swing.JButton();
        JBtnCancela = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JSpQuant = new javax.swing.JSpinner();
        JTxTvalor = new javax.swing.JTextField();
        JTxTDesc = new javax.swing.JTextField();
        JTxtNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JBtnPesquisar = new javax.swing.JButton();
        JTxtPesq = new javax.swing.JTextField();
        JBtnAdicion = new javax.swing.JButton();
        JBtnExcluir = new javax.swing.JButton();
        JBtnLimpaCamp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JBtnLimpa1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jLabel2.setText("Descrição");

        jLabel3.setText("Valor");

        JbtnOK.setText("OK");
        JbtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnOKActionPerformed(evt);
            }
        });

        JBtnCancela.setText("Cancela");
        JBtnCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnCancelaActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade");

        JTxTvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxTvalorActionPerformed(evt);
            }
        });

        JTxTDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxTDescActionPerformed(evt);
            }
        });

        JTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtNomeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Snap ITC", 1, 24)); // NOI18N
        jLabel5.setText("Mercado Senacs");

        JBtnPesquisar.setText("Pesquisar");
        JBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnPesquisarActionPerformed(evt);
            }
        });

        JTxtPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtPesqActionPerformed(evt);
            }
        });

        JBtnAdicion.setText("Adicionar");
        JBtnAdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAdicionActionPerformed(evt);
            }
        });

        JBtnExcluir.setText("Excluir");
        JBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnExcluirActionPerformed(evt);
            }
        });

        JBtnLimpaCamp.setText("Lim.Camp");
        JBtnLimpaCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLimpaCampActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText(" ");
        jScrollPane2.setViewportView(jTextArea1);

        JBtnLimpa1.setText("Limpar");
        JBtnLimpa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnLimpa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(JbtnOK)
                        .addGap(18, 18, 18)
                        .addComponent(JBtnCancela))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel5)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33)
                        .addComponent(JSpQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxtNome)
                            .addComponent(JTxTDesc)
                            .addComponent(JTxTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JTxtPesq)
                        .addGap(49, 49, 49)
                        .addComponent(JBtnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBtnAdicion)
                                .addGap(45, 45, 45)
                                .addComponent(JBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(JBtnLimpaCamp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(JBtnLimpa1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTxtPesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnPesquisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(JTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTxTDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JTxTvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JSpQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JbtnOK)
                            .addComponent(JBtnCancela))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtnAdicion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBtnExcluir)
                        .addComponent(JBtnLimpaCamp)
                        .addComponent(JBtnLimpa1)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnCancelaActionPerformed
        ProdsMercado pd = new ProdsMercado();
        Mercado md = new Mercado();
        pd.getId();
        pd.getNome();
        pd.getQuant();
        pd.getValor();

        JOptionPane.showMessageDialog(rootPane, "Cancelado");
        this.dispose();
        md.setVisible(true);
    }//GEN-LAST:event_JBtnCancelaActionPerformed

    private void JTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtNomeActionPerformed
        ProdsMercado pd = new ProdsMercado();
        //Exibir ex = new Exibir();

        pd.getNome().equalsIgnoreCase("");

        JOptionPane.showMessageDialog(rootPane, pd.getNome());
        ArrayList<ProdsMercado> ArrayList;

//    x

    }//GEN-LAST:event_JTxtNomeActionPerformed

    private void JTxTDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxTDescActionPerformed
        ProdsMercado pd = new ProdsMercado();
        //   Exibir ex = new Exibir();


    }//GEN-LAST:event_JTxTDescActionPerformed

    private void JTxTvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxTvalorActionPerformed
        // ProdsMercado pd = new ProdsMercado();
        //Exibir ex = new Exibir();
        
        JTxTvalor.add(this.JTxTvalor);
    }//GEN-LAST:event_JTxTvalorActionPerformed

    private void JbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnOKActionPerformed
        ProdsMercado pd = new ProdsMercado();
        
        JTxtNome.getName();
        JTxTDesc.getText();
        boolean valida = false;

        valida = true;

        jTextArea1.setText("{ ID = " + pd.getId() + " Nome : " + JTxtNome.getText() + ", " + " Descrição: " + JTxTDesc.getText() + "," + " Valor = " + JTxTvalor.getText() + " Quntidade : " + JSpQuant.getName());
        
        JOptionPane.showMessageDialog(rootPane, "Produto cadastrado");
        //ex.setVisible(true);

    }//GEN-LAST:event_JbtnOKActionPerformed

    private void JBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnPesquisarActionPerformed
        JTextField id = JTxtPesq;
        JTxtPesq.setText(JBtnAdicion.getText());
       //  Pesq(JTxtPesq);
    }//GEN-LAST:event_JBtnPesquisarActionPerformed

    private void JTxtPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtPesqActionPerformed

    }//GEN-LAST:event_JTxtPesqActionPerformed

    private void JBtnAdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAdicionActionPerformed
        ProdsMercado pd = new ProdsMercado();
        Tesr add = new Tesr();
        
      
        
        String nome = JBtnAdicion.getText();
//         incluirProdut(nome);
        
       //incluirProdut(JBtnAdicion.setText("{ ID = " + pd.getId() + " Nome : " + JTxtNome.getText() + ", " + " Descrição: " + JTxTDesc.getText() + "," + " Valor = " + JTxTvalor.getText() + " Quntidade : " + JSpQuant.getName()));
        add.setVisible(false);
    }//GEN-LAST:event_JBtnAdicionActionPerformed

    private void JBtnLimpaCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLimpaCampActionPerformed
          
        JTxtNome.setText("");
        JTxTDesc.setText("");
        JTxTvalor.setText("");
        JSpQuant.setToolTipText("");
       
    }//GEN-LAST:event_JBtnLimpaCampActionPerformed

    private void JBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnExcluirActionPerformed
        
    }//GEN-LAST:event_JBtnExcluirActionPerformed

    private void JBtnLimpa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnLimpa1ActionPerformed
         jTextArea1.setText("");
    }//GEN-LAST:event_JBtnLimpa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tesr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tesr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tesr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tesr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tesr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAdicion;
    private javax.swing.JButton JBtnCancela;
    private javax.swing.JButton JBtnExcluir;
    private javax.swing.JButton JBtnLimpa1;
    private javax.swing.JButton JBtnLimpaCamp;
    private javax.swing.JButton JBtnPesquisar;
    private javax.swing.JSpinner JSpQuant;
    private javax.swing.JTextField JTxTDesc;
    private javax.swing.JTextField JTxTvalor;
    private javax.swing.JTextField JTxtNome;
    private javax.swing.JTextField JTxtPesq;
    private javax.swing.JButton JbtnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
